# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7df5acec66e2d40a82cc82483a678cc0"
name = "generate-product"
handle = "generate-product-1"
application_url = "https://modular-adjustable-hu-yo.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xponent-orka.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://modular-adjustable-hu-yo.trycloudflare.com/auth/callback",
  "https://modular-adjustable-hu-yo.trycloudflare.com/auth/shopify/callback",
  "https://modular-adjustable-hu-yo.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
